version: '3.4'

services:
  web:
    image: nginx:latest
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "${PWD}/default.conf:/etc/nginx/conf.d/default.conf"
    - "${PWD}/pki:/etc/nginx/pki"
    - "${PWD}/public:/usr/share/nginx/html"
  api:
    build: .
